/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameUI from "./Scripts/GameUI"
import HealthBar from "./Scripts/HealthBar"
import Timer from "./Scripts/Timer"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1920;
    static height:number=1080;
    static scaleMode:string="exactfit";
    static screenMode:string="none";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="GameUI.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("Scripts/GameUI.ts",GameUI);
        reg("Scripts/HealthBar.ts",HealthBar);
        reg("Scripts/Timer.ts",Timer);
    }
}
GameConfig.init();