/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Diolog from "./Scripts/Diolog"
import Reader from "./Scripts/Reader"
import FaceReader from "./Scripts/FaceReader"
import commandReader from "./Scripts/commandReader"
import ButtonObject from "./Scripts/ButtonObject"
import Button1 from "./Scripts/Button1"
import Button2 from "./Scripts/Button2"
import Button3 from "./Scripts/Button3"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1920;
    static height:number=1080;
    static scaleMode:string="exactfit";
    static screenMode:string="none";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="Msg.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("Scripts/Diolog.ts",Diolog);
        reg("Scripts/Reader.ts",Reader);
        reg("Scripts/FaceReader.ts",FaceReader);
        reg("Scripts/commandReader.ts",commandReader);
        reg("Scripts/ButtonObject.ts",ButtonObject);
        reg("Scripts/Button1.ts",Button1);
        reg("Scripts/Button2.ts",Button2);
        reg("Scripts/Button3.ts",Button3);
    }
}
GameConfig.init();